server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/standard-investment?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


knife4j:
  # 开启增强功能
  enable: true